### PR TITLE
Remove promise-each dependency

### LINKED ISSUE #275: TypeError: Promise.resolve is not a function
If i don't have `es6-promise` package i get error:
```shell
TypeError: Promise.resolve is not a function
        at /path/to/node_modules/promise-each/index.js:16:16
```

I can do PR if your accept drop `promise-each`.

### PR DESCRIPTION
**Pull request by jonathantneal**
- Resolves #275
- Removes any-promise subdependency
- Removes runtime assert from promise-each

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -174,20 +173,26 @@ function parseStyles(
 ) {
   var statements = parseStatements(result, styles)
 
-  return Promise.resolve(statements).then(promiseEach(function(stmt) {
-    stmt.media = joinMedia(media, stmt.media || [])
+  return Promise.resolve(statements).then(function(stmts) {
+    return stmts.reduce(function(promise, stmt) {
+      return promise.then(function() {
```
Comment (RyanZim) [inline index.js]: LGTM, but perhaps we should have a comment here to explain that this cleverness works on the array in series.

Comment (jonathantneal) [inline index.js]: I’ll add a comment. I’m actually glad to see the `reduce` and `then` terminology used here instead of `each`, because `each` did not make me aware that this was processing the statements in sequence.

Comment (RyanZim) [inline index.js]: @jonathantneal ping?

Comment (jonathantneal) [inline index.js]: Done.

**Comment by RyanZim** [comment]
Thanks!
